query getAnimeByTitle($input: GetAnimeByTitleInput!) {
  getAnimeByTitle(input: $input) {
    title
    author
    company
    is_adult
    genre
    year
    is_ended
    id
    is_show
    image
  }
}
